[providers]
[providers.sourcehut]
ssh = "git@git.sr.ht:~hyro/www"
primary = true
[providers.github]
ssh = "git@github.com:xHyroM/website.git"
[providers.codeberg]
ssh = "git@codeberg.org:xHyroM/website.git"
